<div id="findify-component-update-cart" data-bind="scope: 'findifyUpdateCart'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "findifyUpdateCart": {
                        "component": "Findify_Findify/js/update_cart"
                    }
                }
            }
        }
    }
</script>
